### ISSUE TITLE
nederland24.py throws error

### ISSUE THREAD

**Issue by ernstkui** [bosel/plugin.video.nederland24#14]
Hey bosel,

I like your addon! Used it a lot, but lately it has started to let me down...

I am using a RaspBMC install on a raspberry pi, whenever I start any of the nederland24 channels I get a *Playback failed* check the log files for details. So I did:

This is in the kodi logs:

```
18:35:04 T:2799293504  NOTICE: Thread LanguageInvoker start, auto delete: false
18:35:04 T:2799293504  NOTICE: -->Python Interpreter Initialized<--
18:35:05 T:2799293504  NOTICE: plugin.video.nederland24:: Starting Addon
18:35:05 T:2799293504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.nederland24/nederland24.py", line 187, in <module>
                                                playVideo(url)
                                              File "/home/pi/.kodi/addons/plugin.video.nederland24/nederland24.py", line 163, in playVideo
                                                videopre=re.search(r'http:(.*?)url',page).group()
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
18:35:05 T:3038814208   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nederland24/?url=tvlive%2Fned1%2Fned1.isml%2Fned1.m3u8&mode=playVideo]
18:35:05 T:2799293504  NOTICE: Thread BackgroundLoader start, auto delete: false
```

Do you have any thoughts?

**Comment by ernstkui** [comment]
Forgot to mention: I was running 4.3.0 and tried a rollback to 4.2.3. Found no difference.

**Comment by bosel** [comment]
Seems like something was changed by the npo, I'll look into it. Thanks for reporting

**Comment by ApexAlpha** [comment]
Same here with XBian (latest). All streams result in playback failure see log for more info. If it helps I can post my log here too, but it is probably similar rto Ernst's.

**Comment by bosel** [comment]
862b8de12bb82d4fad034a03a32edc7dca0c8968 should fix this, or you could wait for the official repo to be updated.

**Comment by ernstkui** [comment]
Cool!

**Comment by ApexAlpha** [comment]
Thank you, will try it when I'm home. :)

**Comment by ApexAlpha** [comment]
Works perfectly
