### ISSUE TITLE
sgmllib deprecated gives error.

### ISSUE THREAD

**Issue by pvdl** [bosel/plugin.video.nederland24#16]
See: https://docs.python.org/2/library/sgmllib.html
So basically it is not a error related to the plugin, but related to the Python version.

It gives this error:
```
22:17:55 T:140025459050240   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named sgmllib
                                            Traceback (most recent call last):
                                              File "/home/peter/.kodi/addons/plugin.video.nederland24/nederland24.py", line 24, in <module>
                                                from BeautifulSoup import BeautifulStoneSoup, SoupStrainer
                                              File "/home/peter/.kodi/addons/script.module.beautifulsoup/lib/BeautifulSoup.py", line 86, in <module>
                                                from sgmllib import SGMLParser, SGMLParseError
                                            ImportError: No module named sgmllib
                                            -->End of Python script error report<--
22:17:55 T:140026477856704   ERROR: GetDirectory - Error getting plugin://plugin.video.nederland24/
22:17:55 T:140026477856704   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nederland24/) failed
```

**Comment by pvdl** [comment]
```
 $ python --version
Python 2.7.6
$ kodi --version
15.1 Git:d496682 Media Center Kodi
Copyright (C) 2005-2013 Team Kodi - http://kodi.tv
```

**Comment by bosel** [comment]
Upstream I think, closing this.

**Comment by pvdl** [comment]
I'll try to find an nice solution:
https://stackoverflow.com/questions/1875259/importing-a-module-based-on-installed-python-version
