### ISSUE TITLE
Streams not working

### ISSUE THREAD

**Issue by plusjoost** [bosel/plugin.video.nederland24#28]
The streams do not work anymore (alas). Error log will be posted after dinner :)

//

18:14:47.911 T:1807741856 WARNING: Previous line repeats 300 times.
18:14:47.911 T:1807741856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 410: Gone
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.nederland24/nederland24.py", line 247, in <module>
                                                playVideo(url)
                                              File "/storage/.kodi/addons/plugin.video.nederland24/nederland24.py", line 213, in playVideo
                                                URL = API_URL+BASE_URL+media+"&token=%s" % collect_token()
                                              File "/storage/.kodi/addons/plugin.video.nederland24/nederland24.py", line 146, in collect_token
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 410: Gone
                                            -->End of Python script error report<--
18:14:47.968 T:1961964288   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nederland24/?url=LI_NL1_4188102&mode=playVideo]
18:14:48.731 T:1553986464 WARNING: CWebServer[8080]: invalid response data with range start at 1 and end at 0
18:14:49.244 T:1553986464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 410: Gone
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.nederland24/nederland24.py", line 247, in <module>
                                                playVideo(url)
                                              File "/storage/.kodi/addons/plugin.video.nederland24/nederland24.py", line 213, in playVideo
                                                URL = API_URL+BASE_URL+media+"&token=%s" % collect_token()
                                              File "/storage/.kodi/addons/plugin.video.nederland24/nederland24.py", line 146, in collect_token
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 410: Gone
                                            -->End of Python script error report<--
18:14:49.312 T:1961964288   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nederland24/?url=LI_NL1_4188102&mode=playVideo]
18:14:50.721 T:1762055072 WARNING: CWebServer[8080]: invalid response data with range start at 1 and end at 0
18:22:36.631 T:1553986464 WARNING: Previous line repeats 290 times.

**Comment by plusjoost** [comment]
*closed
