### ISSUE TITLE
Streams changed?

### ISSUE THREAD

**Issue by sciurius** [bosel/plugin.video.nederland24#36]
February 1 ... Seems that the streams have changed again.

**Comment by dutchwhizzman** [comment]
Just confirming that it's currently erroring.

**Comment by ArthurBorsboom** [comment]
I see this error in the kodi.log

```
Error Type: <class 'urllib2.HTTPError'>
Error Contents: HTTP Error 404: Not Found
Traceback (most recent call last):
File "/var/lib/kodi/.kodi/addons/plugin.video.nederland24/nederland24.py", line 241, in <module> playVideo(url)
File "/var/lib/kodi/.kodi/addons/plugin.video.nederland24/nederland24.py", line 208, in playVideo
response = urllib2.urlopen(req)
File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python2.7/urllib2.py", line 435, in open
response = meth(req, response)
File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
http', request, response, code, msg, hdrs)
File "/usr/lib/python2.7/urllib2.py", line 473, in error
return self._call_chain(*args)
File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
result = func(*args)
File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

**Comment by sphaero** [comment]
same here

**Comment by ronalde** [comment]
According to https://github.com/streamlink/streamlink/issues/2289 this is due to DRM encryption.

**Comment by ArthurBorsboom** [comment]
For me the NPO1 live stream started (miracously?) working again.

Did I miss a software update, in which case, thanks for fixing, or did NPO fixed something ?

**Comment by sphaero** [comment]
working again here as well

**Comment by Xorky** [comment]
Coincidentally on february the 2nd the FTA (free to air) HVEC/H.265 codec was introduced.
Unfortunately NPO Radio 1/2/3/4 (visual radio) don`t function properly.

**Comment by sciurius** [comment]
I can confirm the streams work again, without any changes from our side.
This makes me really wonder what happened. The NPO apps didn't blink.
